// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_SaveButton;
lv_obj_t * uic_SliderDim;
lv_obj_t * ui_Setings = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_ContainerLeft = NULL;
lv_obj_t * ui_DropdownSSID = NULL;
lv_obj_t * ui_ButtonSCAN = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_TextAreaPassword = NULL;
lv_obj_t * ui_ButtonENTER = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_CalibrateLevel = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_ContainerRight = NULL;
lv_obj_t * ui_SliderBrightness = NULL;
lv_obj_t * ui_Brightnest = NULL;
lv_obj_t * ui_SwitchAutodim = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_SliderDim = NULL;
lv_obj_t * ui_LabelDimValue = NULL;
lv_obj_t * ui_textareaStart = NULL;
lv_obj_t * ui_textareaEnd = NULL;
lv_obj_t * ui_SaveButton = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_Container6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        global_touch_handler(e);
    }
}

void ui_event_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaPassword);
        _ui_basic_set_property(ui_Keyboard1, _UI_BASIC_PROPERTY_POSITION_X,  0);
        _ui_basic_set_property(ui_Keyboard1, _UI_BASIC_PROPERTY_POSITION_Y,  0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_SliderBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Brightnest, target, "Яркост: ", "%");
    }
}

void ui_event_SwitchAutodim(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_textareaEnd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_textareaStart, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SliderDim, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_SliderDim, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_textareaEnd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_textareaStart, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_SliderDim(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelDimValue, target, "Димиране:", "%");
    }
}

void ui_event_textareaStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_textareaStart);
        _ui_basic_set_property(ui_Keyboard1, _UI_BASIC_PROPERTY_POSITION_X,  0);
        _ui_basic_set_property(ui_Keyboard1, _UI_BASIC_PROPERTY_POSITION_Y,  0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_textareaEnd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_textareaEnd);
        _ui_basic_set_property(ui_Keyboard1, _UI_BASIC_PROPERTY_POSITION_X,  0);
        _ui_basic_set_property(ui_Keyboard1, _UI_BASIC_PROPERTY_POSITION_Y,  0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_SaveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WeatherstationScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_WeatherstationScreen_screen_init);
        (e);
        _ui_checked_set_text_value(ui_Label9, target, "Saved", "Save & Exit");
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Setings_screen_init(void)
{
    ui_Setings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Setings, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Setings, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Setings, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setings, &ui_font_FreeSans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Setings);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(100));
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLeft = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_ContainerLeft, 600);
    lv_obj_set_height(ui_ContainerLeft, lv_pct(53));
    lv_obj_set_x(ui_ContainerLeft, -318);
    lv_obj_set_y(ui_ContainerLeft, -45);
    lv_obj_set_align(ui_ContainerLeft, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerLeft, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerLeft, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerLeft, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownSSID = lv_dropdown_create(ui_ContainerLeft);
    lv_dropdown_set_options(ui_DropdownSSID, "\n");
    lv_obj_set_height(ui_DropdownSSID, 60);
    lv_obj_set_width(ui_DropdownSSID, lv_pct(80));
    lv_obj_set_align(ui_DropdownSSID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownSSID, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DropdownSSID, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownSSID, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSCAN = lv_btn_create(ui_ContainerLeft);
    lv_obj_set_height(ui_ButtonSCAN, 60);
    lv_obj_set_width(ui_ButtonSCAN, lv_pct(18));
    lv_obj_set_x(ui_ButtonSCAN, 61);
    lv_obj_set_y(ui_ButtonSCAN, -2);
    lv_obj_set_align(ui_ButtonSCAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSCAN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSCAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonSCAN, lv_color_hex(0xDB9A19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSCAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonSCAN, &ui_font_FreeSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ButtonSCAN);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SCAN");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x070707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_FreeSansBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaPassword = lv_textarea_create(ui_ContainerLeft);
    lv_obj_set_width(ui_TextAreaPassword, lv_pct(80));
    lv_obj_set_height(ui_TextAreaPassword, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_align(ui_TextAreaPassword, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextAreaPassword, "Pasword");
    lv_textarea_set_placeholder_text(ui_TextAreaPassword, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaPassword, true);
    lv_obj_set_style_text_color(ui_TextAreaPassword, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaPassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonENTER = lv_btn_create(ui_ContainerLeft);
    lv_obj_set_height(ui_ButtonENTER, 60);
    lv_obj_set_width(ui_ButtonENTER, lv_pct(18));
    lv_obj_set_align(ui_ButtonENTER, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonENTER, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonENTER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonENTER, lv_color_hex(0xDB9A19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonENTER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ButtonENTER);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "ENTER");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x0B0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_FreeSansBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrateLevel = lv_btn_create(ui_ContainerLeft);
    lv_obj_set_height(ui_CalibrateLevel, 60);
    lv_obj_set_width(ui_CalibrateLevel, lv_pct(100));
    lv_obj_set_align(ui_CalibrateLevel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrateLevel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrateLevel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CalibrateLevel, lv_color_hex(0xDB9A19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalibrateLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_CalibrateLevel);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Калибриране Нивелир");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_FreeSansBold38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerRight = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_ContainerRight, 600);
    lv_obj_set_height(ui_ContainerRight, lv_pct(53));
    lv_obj_set_x(ui_ContainerRight, -291);
    lv_obj_set_y(ui_ContainerRight, -47);
    lv_obj_set_align(ui_ContainerRight, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerRight, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerRight, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerRight, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ContainerRight, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ContainerRight, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderBrightness = lv_slider_create(ui_ContainerRight);
    lv_slider_set_value(ui_SliderBrightness, 70, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightness, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_height(ui_SliderBrightness, 60);
    lv_obj_set_width(ui_SliderBrightness, lv_pct(100));
    lv_obj_set_x(ui_SliderBrightness, 181);
    lv_obj_set_y(ui_SliderBrightness, -66);
    lv_obj_set_align(ui_SliderBrightness, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderBrightness, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0xDBD5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBrightness, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0xDBD5D5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBrightness, 50, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0xDB9A19), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderBrightness, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SliderBrightness, LV_BORDER_SIDE_FULL, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Brightnest = lv_label_create(ui_SliderBrightness);
    lv_obj_set_width(ui_Brightnest, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brightnest, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Brightnest, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brightnest, "Яркост");
    lv_obj_set_style_text_color(ui_Brightnest, lv_color_hex(0x0D0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Brightnest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Brightnest, &ui_font_FreeSansBold38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchAutodim = lv_switch_create(ui_ContainerRight);
    lv_obj_set_height(ui_SwitchAutodim, 60);
    lv_obj_set_width(ui_SwitchAutodim, lv_pct(100));
    lv_obj_set_align(ui_SwitchAutodim, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SwitchAutodim, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchAutodim, lv_color_hex(0xDBD5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchAutodim, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SwitchAutodim, lv_color_hex(0xDBD5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SwitchAutodim, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SwitchAutodim, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SwitchAutodim, lv_color_hex(0xDB9A19), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchAutodim, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SwitchAutodim, lv_color_hex(0xDBD5D5), LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_SwitchAutodim);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 18);
    lv_obj_set_y(ui_Label13, -3);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Димиране ON/OFF");
    lv_obj_add_state(ui_Label13, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x0D0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_FreeSansBold38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderDim = lv_slider_create(ui_ContainerRight);
    lv_slider_set_range(ui_SliderDim, 0, 30);
    lv_slider_set_value(ui_SliderDim, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderDim) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderDim, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_SliderDim, 60);
    lv_obj_set_width(ui_SliderDim, lv_pct(100));
    lv_obj_set_align(ui_SliderDim, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderDim, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderDim, lv_color_hex(0xDBD5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderDim, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderDim, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderDim, lv_color_hex(0xDBD5D5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderDim, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderDim, lv_color_hex(0xDB9A19), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderDim, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderDim, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderDim, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderDim, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelDimValue = lv_label_create(ui_SliderDim);
    lv_obj_set_width(ui_LabelDimValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDimValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDimValue, 2);
    lv_obj_set_y(ui_LabelDimValue, 0);
    lv_obj_set_align(ui_LabelDimValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDimValue, "Димиране: 20%");
    lv_obj_set_style_text_color(ui_LabelDimValue, lv_color_hex(0x0B0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDimValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDimValue, &ui_font_FreeSansBold38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textareaStart = lv_textarea_create(ui_ContainerRight);
    lv_obj_set_height(ui_textareaStart, 60);
    lv_obj_set_width(ui_textareaStart, lv_pct(45));
    lv_obj_set_align(ui_textareaStart, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_textareaStart, "22:30");
    lv_textarea_set_placeholder_text(ui_textareaStart, "Placeholder...");
    lv_obj_set_style_text_font(ui_textareaStart, &ui_font_FreeSans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textareaEnd = lv_textarea_create(ui_ContainerRight);
    lv_obj_set_height(ui_textareaEnd, 60);
    lv_obj_set_width(ui_textareaEnd, lv_pct(45));
    lv_obj_set_align(ui_textareaEnd, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_textareaEnd, "07:30");
    lv_textarea_set_placeholder_text(ui_textareaEnd, "Placeholder...");
    lv_obj_set_style_text_font(ui_textareaEnd, &ui_font_FreeSans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveButton = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_SaveButton, 300);
    lv_obj_set_height(ui_SaveButton, 70);
    lv_obj_set_x(ui_SaveButton, -107);
    lv_obj_set_y(ui_SaveButton, 200);
    lv_obj_set_align(ui_SaveButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SaveButton, lv_color_hex(0xDB9A19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SaveButton, lv_color_hex(0x0C0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_SaveButton);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Save & Exit");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_FreeSansBold38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Container6);
    lv_obj_set_height(ui_Keyboard1, 200);
    lv_obj_set_width(ui_Keyboard1, lv_pct(99));
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 258);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_FLOATING);     /// Flags

    lv_obj_set_style_text_font(ui_Keyboard1, &lv_font_montserrat_14, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAutodim, ui_event_SwitchAutodim, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderDim, ui_event_SliderDim, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_textareaStart, ui_event_textareaStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_textareaEnd, ui_event_textareaEnd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveButton, ui_event_SaveButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container6, ui_event_Container6, LV_EVENT_ALL, NULL);
    uic_SliderDim = ui_SliderDim;
    uic_SaveButton = ui_SaveButton;

}

void ui_Setings_screen_destroy(void)
{
    if(ui_Setings) lv_obj_del(ui_Setings);

    // NULL screen variables
    ui_Setings = NULL;
    ui_Container6 = NULL;
    ui_ContainerLeft = NULL;
    ui_DropdownSSID = NULL;
    ui_ButtonSCAN = NULL;
    ui_Label1 = NULL;
    ui_TextAreaPassword = NULL;
    ui_ButtonENTER = NULL;
    ui_Label2 = NULL;
    ui_CalibrateLevel = NULL;
    ui_Label10 = NULL;
    ui_ContainerRight = NULL;
    ui_SliderBrightness = NULL;
    ui_Brightnest = NULL;
    ui_SwitchAutodim = NULL;
    ui_Label13 = NULL;
    uic_SliderDim = NULL;
    ui_SliderDim = NULL;
    ui_LabelDimValue = NULL;
    ui_textareaStart = NULL;
    ui_textareaEnd = NULL;
    uic_SaveButton = NULL;
    ui_SaveButton = NULL;
    ui_Label9 = NULL;
    ui_Keyboard1 = NULL;

}
