// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETINGS_H
#define UI_SETINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Setings
extern void ui_Setings_screen_init(void);
extern void ui_Setings_screen_destroy(void);
extern lv_obj_t * ui_Setings;
extern void ui_event_Container6(lv_event_t * e);
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_ContainerLeft;
extern lv_obj_t * ui_DropdownSSID;
extern lv_obj_t * ui_ButtonSCAN;
extern lv_obj_t * ui_Label1;
extern void ui_event_TextAreaPassword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPassword;
extern lv_obj_t * ui_ButtonENTER;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_CalibrateLevel;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_ContainerRight;
extern void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_Brightnest;
extern void ui_event_SwitchAutodim(lv_event_t * e);
extern lv_obj_t * ui_SwitchAutodim;
extern lv_obj_t * ui_Label13;
extern void ui_event_SliderDim(lv_event_t * e);
extern lv_obj_t * ui_SliderDim;
extern lv_obj_t * ui_LabelDimValue;
extern void ui_event_textareaStart(lv_event_t * e);
extern lv_obj_t * ui_textareaStart;
extern void ui_event_textareaEnd(lv_event_t * e);
extern lv_obj_t * ui_textareaEnd;
extern void ui_event_SaveButton(lv_event_t * e);
extern lv_obj_t * ui_SaveButton;
extern lv_obj_t * ui_Label9;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SliderDim;
extern lv_obj_t * uic_SaveButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

