// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_WEATHERSTATIONSCREEN_H
#define UI_WEATHERSTATIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WeatherstationScreen
extern void ui_WeatherstationScreen_screen_init(void);
extern void ui_WeatherstationScreen_screen_destroy(void);
extern void ui_event_WeatherstationScreen(lv_event_t * e);
extern lv_obj_t * ui_WeatherstationScreen;
extern void ui_event_Container4(lv_event_t * e);
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image9;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Out;
extern lv_obj_t * ui_NameOut;
extern lv_obj_t * ui_PanelOut;
extern lv_obj_t * ui_WeatherIcon;
extern lv_obj_t * ui_PanelOut1;
extern lv_obj_t * ui_LineTempCurrent;
extern lv_obj_t * ui_TempCurrent;
extern lv_obj_t * ui_TempCurrentUnit;
extern lv_obj_t * ui_LineCloudsUvCurrent;
extern lv_obj_t * ui_PanelCloudsCurrent;
extern lv_obj_t * ui_CloudsCurrentIcon;
extern lv_obj_t * ui_CloudsCurrent;
extern lv_obj_t * ui_CloudsCurrentUnit;
extern lv_obj_t * ui_PanelUvCurrent;
extern lv_obj_t * ui_UvCurrentIcon;
extern lv_obj_t * ui_UvCurrent;
extern lv_obj_t * ui_PanelOut2;
extern lv_obj_t * ui_WindDirectionCurrentIcon;
extern lv_obj_t * ui_PanelWindCurrent;
extern lv_obj_t * ui_LineWindSpeedCurrent;
extern lv_obj_t * ui_WindSpeedCurrent;
extern lv_obj_t * ui_WindSpeedCurrentUnit;
extern lv_obj_t * ui_LineWindGustCurrent;
extern lv_obj_t * ui_WindGustCurrent;
extern lv_obj_t * ui_WindGustCurrentUnit;
extern lv_obj_t * ui_PanelSunCurrent;
extern lv_obj_t * ui_LineSunriseCurrent;
extern lv_obj_t * ui_SunriseCurrentIcon;
extern lv_obj_t * ui_SunriseCurrent;
extern lv_obj_t * ui_LineSunsetCurrent;
extern lv_obj_t * ui_SunsetCurrentIcon;
extern lv_obj_t * ui_SunsetCurrent;
extern lv_obj_t * ui_PanelSea;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_TempSea;
extern lv_obj_t * ui_Insaid;
extern lv_obj_t * ui_NameInsaid;
extern lv_obj_t * ui_LineTempInsaid;
extern lv_obj_t * ui_TempInsaid;
extern lv_obj_t * ui_TempInsaidUnit;
extern lv_obj_t * ui_LineHumidityInsaid;
extern lv_obj_t * ui_IconHumidityInsaid;
extern lv_obj_t * ui_HumidityInsaid;
extern lv_obj_t * ui_HumidityBaseIcon;
extern lv_obj_t * ui_LinePressure4;
extern lv_obj_t * ui_ImagePressure4;
extern lv_obj_t * ui_Pressure4;
extern lv_obj_t * ui_Pressure1Unit2;
extern lv_obj_t * ui_LineVOX;
extern lv_obj_t * ui_ImageVOX;
extern lv_obj_t * ui_VOX;
extern lv_obj_t * ui_HourlyChart;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_StartBattery2;
extern lv_obj_t * ui_NameStartBattery;
extern lv_obj_t * ui_LineStartBattery;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_StartBattery;
extern lv_obj_t * ui_UnitStartBattery;
extern lv_obj_t * ui_BarStartBattery;
extern lv_obj_t * ui_ClearWather1;
extern lv_obj_t * ui_NameClearWather;
extern lv_obj_t * ui_LineClearWather;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_ClearWather;
extern lv_obj_t * ui_BarClearWather;
extern lv_obj_t * ui_CampBattery1;
extern lv_obj_t * ui_NameCampBattery;
extern lv_obj_t * ui_LineCampBattery;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_CampBattery;
extern lv_obj_t * ui_UnitCampBattery;
extern lv_obj_t * ui_BarCampBattery;
extern lv_obj_t * ui_GreyWather1;
extern lv_obj_t * ui_NameGreyWather;
extern lv_obj_t * ui_LineGreyWather;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_GreyWather;
extern lv_obj_t * ui_BarGreyWather;
extern lv_obj_t * ui_Solar1;
extern lv_obj_t * ui_NameSolar;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_SolarWat;
extern lv_obj_t * ui_SolarVolt;
extern lv_obj_t * ui_Sensor2;
extern lv_obj_t * ui_Name7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_SolarCurent;
extern lv_obj_t * ui_SolarStatus;
extern lv_obj_t * ui_WC1;
extern lv_obj_t * ui_NameWC;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_ImageWC;
extern lv_obj_t * ui_StatusWC;
extern lv_obj_t * ui_Frige1;
extern lv_obj_t * ui_NameFrige;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_LineTempFrige;
extern lv_obj_t * ui_TempFrige;
extern lv_obj_t * ui_TempFrigeUnit;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_DailyChart;
extern lv_obj_t * ui_Nivel2;
extern lv_obj_t * ui_Nivel;
extern void ui_event_SliderRoll(lv_event_t * e);
extern lv_obj_t * ui_SliderRoll;
extern lv_obj_t * ui_LabelRoll;
extern void ui_event_SliderPitch(lv_event_t * e);
extern lv_obj_t * ui_SliderPitch;
extern lv_obj_t * ui_LabelPitch;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

