#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    AUDIO_EVENT_NONE = 0,

    // System
    AUDIO_EVENT_BOOT,
    AUDIO_EVENT_WELCOME,
    AUDIO_EVENT_DONE,
    AUDIO_EVENT_SAVED,
    AUDIO_EVENT_CANCELED,
    AUDIO_EVENT_SETTINGS_APPLIED,

    // Connectivity
    AUDIO_EVENT_WIFI_CONNECTED,
    AUDIO_EVENT_WIFI_DISCONNECTED,
  

    // GPS
    AUDIO_EVENT_GPS_FIX,
    AUDIO_EVENT_GPS_LOST,

    // Alerts
    AUDIO_EVENT_ALARM,
    AUDIO_EVENT_CO2_HIGH,
    AUDIO_EVENT_TEMPERATURE_HIGH,


    // Battery
    AUDIO_EVENT_BATTERY_LOW,
    AUDIO_EVENT_BATTERY_CRITICAL,
    AUDIO_EVENT_START_BATTERY_LOW,
    AUDIO_EVENT_START_BATTERY_CRITICAL,

    // UI
    AUDIO_EVENT_TOUCH,
    AUDIO_EVENT_BUTTON,

    // Camper-specific
    AUDIO_EVENT_TOILET_FULL,
    AUDIO_EVENT_WATER_LOW,

    // Hours (08–24)
    AUDIO_EVENT_HOUR_01,
    AUDIO_EVENT_HOUR_02,
    AUDIO_EVENT_HOUR_03,
    AUDIO_EVENT_HOUR_04,
    AUDIO_EVENT_HOUR_05,
    AUDIO_EVENT_HOUR_06,
    AUDIO_EVENT_HOUR_07,
    AUDIO_EVENT_HOUR_08,
    AUDIO_EVENT_HOUR_09,
    AUDIO_EVENT_HOUR_10,
    AUDIO_EVENT_HOUR_11,
    AUDIO_EVENT_HOUR_12,
    AUDIO_EVENT_HOUR_13,
    AUDIO_EVENT_HOUR_14,
    AUDIO_EVENT_HOUR_15,
    AUDIO_EVENT_HOUR_16,
    AUDIO_EVENT_HOUR_17,
    AUDIO_EVENT_HOUR_18,
    AUDIO_EVENT_HOUR_19,
    AUDIO_EVENT_HOUR_20,
    AUDIO_EVENT_HOUR_21,
    AUDIO_EVENT_HOUR_22,
    AUDIO_EVENT_HOUR_23,
    AUDIO_EVENT_HOUR_24,

    AUDIO_EVENT_MAX
} audio_event_t;

const char *audio_event_get_path(audio_event_t event);

#ifdef __cplusplus
}
#endif
