// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_WeatherstationScreen.h"
#include "screens/ui_Setings.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_map_png);    // assets/map.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_optimizing64_png);    // assets/optimizing64.png
LV_IMG_DECLARE(ui_img_04d_png);    // assets/04d.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png
LV_IMG_DECLARE(ui_img_uv_png);    // assets/uv.png
LV_IMG_DECLARE(ui_img_1101766569);    // assets/right-arrow.png
LV_IMG_DECLARE(ui_img_sunrise_png);    // assets/sunrise.png
LV_IMG_DECLARE(ui_img_sunset_png);    // assets/sunset.png
LV_IMG_DECLARE(ui_img_1336290374);    // assets/high-temperature.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_pressure_png);    // assets/pressure.png
LV_IMG_DECLARE(ui_img_1300464162);    // assets/carbon-neutral.png
LV_IMG_DECLARE(ui_img_start_bat1_png);    // assets/Start BAT1.png
LV_IMG_DECLARE(ui_img_1266565932);    // assets/008-water-tank.png
LV_IMG_DECLARE(ui_img_1036513893);    // assets/002-house-on-wheels.png
LV_IMG_DECLARE(ui_img_241688965);    // assets/006-paintball.png
LV_IMG_DECLARE(ui_img_1164345568);    // assets/005-solar64.png
LV_IMG_DECLARE(ui_img_1754312304);    // assets/012-power64.png
LV_IMG_DECLARE(ui_img_1221855485);    // assets/toilet-seat01.png
LV_IMG_DECLARE(ui_img_freezing_png);    // assets/freezing.png
LV_IMG_DECLARE(ui_img_1617849300);    // assets/004-camper-van.png
LV_IMG_DECLARE(ui_img_157047313);    // assets/005-solar-cell.png
LV_IMG_DECLARE(ui_img_1017807020);    // assets/012-power-up-1.png
LV_IMG_DECLARE(ui_img_01d_png);    // assets/01d.png
LV_IMG_DECLARE(ui_img_01n_png);    // assets/01n.png
LV_IMG_DECLARE(ui_img_02d_png);    // assets/02d.png
LV_IMG_DECLARE(ui_img_02n_png);    // assets/02n.png
LV_IMG_DECLARE(ui_img_03d_png);    // assets/03d.png
LV_IMG_DECLARE(ui_img_03n_png);    // assets/03n.png
LV_IMG_DECLARE(ui_img_04n_png);    // assets/04n.png
LV_IMG_DECLARE(ui_img_09d_png);    // assets/09d.png
LV_IMG_DECLARE(ui_img_09n_png);    // assets/09n.png
LV_IMG_DECLARE(ui_img_10d_png);    // assets/10d.png
LV_IMG_DECLARE(ui_img_10n_png);    // assets/10n.png
LV_IMG_DECLARE(ui_img_11d_png);    // assets/11d.png
LV_IMG_DECLARE(ui_img_11n_png);    // assets/11n.png
LV_IMG_DECLARE(ui_img_13d_png);    // assets/13d.png
LV_IMG_DECLARE(ui_img_13n_png);    // assets/13n.png
LV_IMG_DECLARE(ui_img_50d_png);    // assets/50d.png
LV_IMG_DECLARE(ui_img_50n_png);    // assets/50n.png
LV_IMG_DECLARE(ui_img_1706833765);    // assets/artificial-intelligence.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_optimizing_png);    // assets/optimizing.png
LV_IMG_DECLARE(ui_img_1110708744);    // assets/toilet-seat.png
LV_IMG_DECLARE(ui_img_2072039010);    // assets/toilet-seat0.png
LV_IMG_DECLARE(ui_img_2072040035);    // assets/toilet-seat1.png
LV_IMG_DECLARE(ui_img_uhr_png);    // assets/uhr.png
LV_IMG_DECLARE(ui_img_warming_png);    // assets/warming.png
LV_IMG_DECLARE(ui_img_wc_png);    // assets/wc.png
LV_IMG_DECLARE(ui_img_wifi1_png);    // assets/wifi1.png

// FONTS
LV_FONT_DECLARE(ui_font_FreeSaansBold52);
LV_FONT_DECLARE(ui_font_FreeSaansBold58);
LV_FONT_DECLARE(ui_font_FreeSans10);
LV_FONT_DECLARE(ui_font_FreeSans14);
LV_FONT_DECLARE(ui_font_FreeSans16);
LV_FONT_DECLARE(ui_font_FreeSans18);
LV_FONT_DECLARE(ui_font_FreeSans20);
LV_FONT_DECLARE(ui_font_FreeSans22);
LV_FONT_DECLARE(ui_font_FreeSans24);
LV_FONT_DECLARE(ui_font_FreeSansBold24);
LV_FONT_DECLARE(ui_font_FreeSansBold38);
LV_FONT_DECLARE(ui_font_FreeSansBold44);
LV_FONT_DECLARE(ui_font_FreeSansBold46);
LV_FONT_DECLARE(ui_font_FreeSansBold48);
LV_FONT_DECLARE(ui_font_montserrat_24);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
